parameters:
  - name: "buildConfiguration"
    default: "Release"
    type: string
  - name: "buildVersion"
    default: ""
    type: string
  - name: "publishEnabled"
    default: "false"
    type: string
  - name: "publishFeed"
    default: ""
    type: string

jobs:
  - job: "BuildNugets"
    displayName: "Build Nugets"
    workspace:
      clean: all
    pool:
      vmImage: windows-2019
    variables:
      NetCoreSDKVersion: 5.0.x
      NuGetVersion: 5.8.x
      nugetOutputPath: $(Build.StagingDirectory)/nupkgs

    steps:
      - task: UseDotNet@2
        displayName: Use .Net Core SDK
        inputs:
          version: $(NetCoreSDKVersion)

      - task: NuGetToolInstaller@1
        displayName: Use NuGet
        inputs:
          versionSpec: $(NuGetVersion)
          checkLatest: true

      - task: PowerShell@2
        displayName: Generate NuGet packages
        inputs:
          filePath: Generate-NuGets.ps1
          arguments: "-Version ${{ parameters.buildVersion }} -outputfolder $(nugetOutputPath) -BuildConfiguration ${{ parameters.buildConfiguration }}"

      - task: PublishBuildArtifacts@1
        displayName: "Publish Artifact: NuGets"
        inputs:
          PathtoPublish: $(nugetOutputPath)
          ArtifactName: NuGets

      - task: NuGetCommand@2
        displayName: "Push NuGets to feed"
        enabled: ${{ parameters.publishEnabled }}
        condition: and(succeeded(), ne('${{ parameters.publishFeed }}', ''))
        inputs:
          command: push
          searchPatternPush: $(nugetOutputPath)/**/*.nupkg;!$(nugetOutputPath)/**/*.symbols.nupkg
          nuGetFeedType: external
          publishFeedCredentials: ${{ parameters.publishFeed }}
