name: $(Date:yyyy)$(Date:.M)$(Date:.d)$(Rev:.r)

trigger: none
pr: none

stages:
  - stage: NugetBuild
    displayName: "Build Nugets"
    jobs:
      - template: "templates/build-nugets.yml"
        parameters:
          buildConfiguration: Release
          buildVersion: "$(Build.BuildNumber)"
          publishEnabled: true
          publishFeed: "Evergine.Stable"
