name: $(Date:yyyy)$(Date:.M)$(Date:.d)$(Rev:.r)-rolling

trigger:
  batch: true
  branches:
    include:
      - master
pr:
  autoCancel: true
  branches:
    include:
      - master

stages:
  - stage: NugetBuild
    displayName: "Build Nugets"
    jobs:
      - template: "templates/build-nugets.yml"
        parameters:
          buildConfiguration: Release
          buildVersion: "$(Build.BuildNumber)"
          publishEnabled: false
          publishFeed: ""
