<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<Copyright>Copyright (c) Evergine 2026</Copyright>
		<Authors>Evergine Team</Authors>
		<Company>Plain Concepts</Company>
		<Description>Low-level bindings for OpenGL used in Evergine</Description>
		<RepositoryUrl>https://github.com/EvergineTeam/OpenGL.NET</RepositoryUrl>
		<PackageIcon>icon.png</PackageIcon>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<PackageReadmeFile>README.md</PackageReadmeFile>
	</PropertyGroup>

	<ItemGroup>
		<None Include="..\..\icon.png" Pack="true" PackagePath="\" Visible="false" />
		<None Include="..\..\README.md" Pack="true" PackagePath="\" Visible="false" />
	</ItemGroup>
</Project>
